name: pixer_workspace
description: A workspace for the pixer package.

environment:
  sdk: ^3.10.7

workspace:
  - packages/pixer
  - packages/benchmarks
  # - upscale_flutter

hooks:
  user_defines:
    pixer:
      local_build: true
