name: fast_image
description: A fast image processing package.
version: 0.0.2
resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  code_assets: ^1.0.0
  ffi: ^2.1.4
  hooks: ^1.0.0
  native_toolchain_rs: ^1.0.0
  crypto: ^3.0.7

dev_dependencies:
  ffigen: ^20.1.1
  lints: ^6.0.0
  test: ^1.25.6
